-- admin_actions already created in 008_contests.sql — CREATE IF NOT EXISTS is a safe no-op
CREATE TABLE IF NOT EXISTS admin_actions (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action      TEXT        NOT NULL,
  target_type TEXT        DEFAULT NULL,
  target_id   UUID        DEFAULT NULL,
  metadata    JSONB       NOT NULL DEFAULT '{}',
  created_at  TIMESTAMPTZ DEFAULT now()
);

-- promo_codes: discount / pro-grant codes generated by admins
CREATE TABLE IF NOT EXISTS promo_codes (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  code         TEXT        UNIQUE NOT NULL,
  discount_pct INTEGER     NOT NULL DEFAULT 0
               CHECK (discount_pct BETWEEN 0 AND 100),
  max_uses     INTEGER     NOT NULL DEFAULT 1,
  uses         INTEGER     NOT NULL DEFAULT 0,
  grants_pro   BOOLEAN     NOT NULL DEFAULT false,
  pro_days     INTEGER     NOT NULL DEFAULT 30,
  expires_at   TIMESTAMPTZ DEFAULT NULL,
  created_by   UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  is_active    BOOLEAN     NOT NULL DEFAULT true,
  created_at   TIMESTAMPTZ DEFAULT now()
);

-- promo_code_redemptions: per-user redemption log (prevents double-redeem)
CREATE TABLE IF NOT EXISTS promo_code_redemptions (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  code_id    UUID        NOT NULL REFERENCES promo_codes(id) ON DELETE CASCADE,
  user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  redeemed_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (code_id, user_id)
);

-- Add flags JSONB column to users for structured flag history
-- (is_flagged boolean already exists for quick bool checks)
ALTER TABLE users ADD COLUMN IF NOT EXISTS flags JSONB NOT NULL DEFAULT '[]';

-- subscription_status and pro_expires_at already exist on profiles (002_profiles.sql) — no ALTER needed

CREATE INDEX IF NOT EXISTS idx_promo_codes_code      ON promo_codes(code);
CREATE INDEX IF NOT EXISTS idx_promo_codes_active    ON promo_codes(is_active);
CREATE INDEX IF NOT EXISTS idx_redemptions_user      ON promo_code_redemptions(user_id);
CREATE INDEX IF NOT EXISTS idx_admin_actions_admin   ON admin_actions(admin_id);
CREATE INDEX IF NOT EXISTS idx_admin_actions_target  ON admin_actions(target_id);
